### ISSUE TITLE
How to handle `application/api.vnd+json` requests and responses?

### ISSUE THREAD

**Issue by cesarizu** [AgilionApps/ja_resource#25]
Hello, I'm trying to implement an api and I have a couple of problems. I've tried to handle `api.vnd+json` requests and responses but it's not working. What I've done so far:

1. Add "mimes" configuration like indicated here: https://hexdocs.pm/plug/Plug.MIME.html
2. Add `plug :accepts, ["json-api"]` to the `:api` pipeline

With this, when I send a request with `Accept: application/vnd.api+json`, I get a "HTTP/1.1 406 Not Acceptable" response. If I change the "json-api" bits to "json" the server accepts the json-api request but responds with content-type equal to `application/json; charset=utf-8` instead of `application/vnd.api+json; charset=utf-8`.

Is there a way to ask ja_resource to use the json-api content type for requests and responses? Am I missing something?

**Comment by alanpeabody** [comment]
Hi, @cesarizu,

I should probably add this to the documentation, but basically we rely on sibling library ja_serializer for the content type negotation currently. You can check out the instructions here: https://github.com/AgilionApps/ja_serializer#phoenix-usage

If you are still having issues after that, let me know!

**Comment by cesarizu** [comment]
That makes total sense... thanks a lot

**Comment by alanpeabody** [comment]
Let me know if you have any more issues!
