### ISSUE TITLE
How to add top-level meta for Scrivener pagination

### ISSUE THREAD

**Issue by begedin** [AgilionApps/ja_resource#33]
In https://github.com/AgilionApps/ja_resource/pull/11#issuecomment-184238883, there was a brief mention that passing the results of `MyApp.Repo.paginate/2` handles adding the meta to the rendered json-api payload.

>Yeah, for pagination I would potentially like to make it super easy to add. I need to think through it a bit more, but on the serialization side the just passing the results of MyApp.Repo.paginate/2 handles setting the meta for you. It is actually calling paginate with the correct params that needs to be added here.

However, this is not the case, in my experience.

It adds the `links` property, which is done by `ja_serializer` and usually looks something like:

```Elixir
links = %{
  first: "http://example.com/api/v1/posts?page[cursor]=1&page[per]=20",
  prev: nil
  next: "http://example.com/api/v1/posts?page[cursor]=20&page[per]=20",
  last: "http://example.com/api/v1/posts?page[cursor]=60&page[per]=20"
}
```

It does not, however, add the `meta` property, which would look something like:

```elixir
meta = %{
  current_page: page.page_number,
  page_size: page.page_size,
  total_pages: page.total_pages,
  total_records: page.total_entries
}
```

Am I missing some setting? Looking through the code, I was not able to find anything.

If it is in fact actually missing, it would be relatively simple to add the option by modifying hte following bit of code:

```elixir
def respond(models, conn, controller) do
  opts = controller.serialization_opts(conn, conn.query_params)
  Phoenix.Controller.render(conn, :index, data: models, opts: opts)
end
```

We simply call `controller.serialization_otps(models, conn, conn.query_params)` instead, thus passing in the models (which will be the scrivener page, if `handle_index_query` returns a scrivener page).

However, I'm not really sure if this is the addon which ought to handle the meta. Since `ja_serializer` already handles the `links` automatically, maybe it should also define a `meta` callback on the serializer level, instead of just defining an individual resource level `meta` callback, to attach to each individual resource in the rendered payload.

As is, `ja_serializer` allows setting the value for top level meta when calling `Phoenix.Controller.render`, but then `ja_resource` blocks us from doing that, by wrapping the render call inside the `response` function, and then letting us define the serialization options based on `conn` and `conn.query_params` alone, not depending on the data being rendered at all.

I get that from `conn.query_params`, in some cases, we could figure out some paging meta, but not always, and not all of it.

**Comment by alanpeabody** [comment]
Hey @begedin, your right: there isn't currently any "built in" pagination meta support because it isn't part of the JSON-API spec.

It does seem like there should be a way to set meta in general via ja_resource (as ja_serializer supports it). Serialization opts is where this make sense to me, and it does seem like that callback should indeed get the model, but maybe as the second or third argument to keep the consistency of the first argument as the conn.

I don't believe there should be any meta data automatically added, but hooking in seems very reasonable.
